parameters:
  subscriptionName:
  environmentName:
  environmentCategory:
  applicationCode:
  applicationShortCode:
  imageTag:
  blueGreen:
  serviceName:
  servicePort:
  serviceProbesEnabled:


jobs:
  - template: get-approval.yaml
    parameters:
      environmentName: ${{parameters.environmentName}}
      
  - job: deploy
    displayName: Deploy
    variables:
      - template: variables-all.yaml
      - name: aksName
        value: ${{parameters.applicationCode}}-$(aksPartialName)-${{parameters.environmentCategory}}
      - name: resourceGroupName
        value: $(resourceGroupPartialName)-iot-${{parameters.applicationShortCode}}-${{parameters.environmentCategory}}
    steps:
      - template: print-pipeline-resource-variables.yaml
        parameters:
          pipelineResourceName: infra

      - download: none

      - script: |-
          echo "subscriptionName: ${{parameters.subscriptionName}}"
          echo "environmentName: ${{parameters.environmentName}}"
          echo "environmentCategory: ${{parameters.environmentCategory}}"
          echo "applicationCode: ${{parameters.applicationCode}}"
          echo "aksPartialName: ${{parameters.aksPartialName}}"
          echo "resourceGroupPartialName: ${{parameters.resourceGroupPartialName}}"
          echo "aksName: $(aksName)"
          echo "resourceGroupName: $(resourceGroupName)"
          echo "helmVersion: $(helmVersion)"
          echo "serviceName: ${{parameters.serviceName}}"
          echo "servicePort: ${{parameters.servicePort}}"
          echo "serviceProbesEnabled: ${{parameters.serviceProbesEnabled}}"
          echo "blueGreen: ${{parameters.blueGreen}}"
        displayName: Print job variables

      - ${{ if eq(parameters.blueGreen,false) }}:
        - template: steps-deploy-individual-service.yaml
          parameters:
            aksName: $(aksName)
            resourceGroupName: $(resourceGroupName)
            subscriptionName: ${{parameters.subscriptionName}}
            serviceName: ${{parameters.serviceName}}
            servicePort: ${{parameters.servicePort}}
            serviceProbesEnabled: ${{parameters.serviceProbesEnabled}}
            helmVersion: $(helmVersion)
            imageTag: ${{parameters.imageTag}}

      - ${{ if eq(parameters.blueGreen,true) }}:
        - template: steps-deploy-blue-green-service.yaml
          parameters:
            aksName: $(aksName)
            resourceGroupName: $(resourceGroupName)
            subscriptionName: ${{parameters.subscriptionName}}
            blueServiceName: ${{parameters.serviceName}}-blue
            greenServiceName: ${{parameters.serviceName}}-green
            serviceName: ${{parameters.serviceName}}
            servicePort: ${{parameters.servicePort}}
            serviceProbesEnabled: ${{parameters.serviceProbesEnabled}}
            helmVersion: $(helmVersion)
            imageTag: ${{parameters.imageTag}}
            type: blue


  - job: addKey
    displayName: Update Application Configuration with BuildNumber
    variables:
      - template: variables-all.yaml
      - name: appConfigurationName
        value: ${{parameters.applicationCode}}-$(appConfigurationPartialName)-${{parameters.environmentCategory}}

    dependsOn:
     - deploy
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{parameters.subscriptionName}}
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |-
            set -Eeuxo pipefail
            az appconfig kv set --key Global:BuildNumber --value $(Build.BuildId) --name $(appConfigurationName)  --yes




