parameters:
  subscriptionName:
  environmentName:
  environmentCategory:
  applicationCode:
  applicationShortCode:
  imageTag:
  blueGreen:

jobs:
      
  - job: deploy
    displayName: Deploy
    variables: 
      - name: blueGreen
        value: $[eq(variables['blueGreen-acsDev'], 'yes')]
    steps:

      - ${{ if eq(variables['blueGreen'],'False') }}:
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{parameters.subscriptionName}}
            addSpnToEnvironment: true
            scriptLocation: inlineScript
            scriptType: bash
            inlineScript: |-
              set -Eeuxo pipefail
              echo "blueGreen-falsecheck":$(blueGreen-acsDev)
              echo "blueGreen-falsecheck":${{parameters.blueGreen}}
              echo "blueGreen": $(blueGreen)
              echo "go to  individual services..."

      - ${{ if eq(variables['blueGreen'],'True') }}:
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{parameters.subscriptionName}}
            addSpnToEnvironment: true
            scriptLocation: inlineScript
            scriptType: bash
            inlineScript: |-
              set -Eeuxo pipefail
              echo "blueGreen-truecheck":$(blueGreen-acsDev)
              echo "blueGreen-truecheck":${{parameters.blueGreen}}
              echo "blueGreen": $(blueGreen) 
              echo "go to  bluegreen services..."


      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{parameters.subscriptionName}}
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |-
            set -Eeuxo pipefail
            echo "non-blueGreen":$(blueGreen-acsDev)
            echo "non-blueGreen":${{parameters.blueGreen}}
            echo "blueGreen": $(blueGreen) 

                      






