parameters:
  subscriptionName:
  environmentName:
  environmentCategory:
  applicationCode:
  applicationShortCode:
  imageTag:
  blueGreen:

jobs:
      
  - job: deploy
    displayName: Deploy
    steps:

      - ${{ if eq(parameters.blueGreen,'false') }}:
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{parameters.subscriptionName}}
            addSpnToEnvironment: true
            scriptLocation: inlineScript
            scriptType: bash
            inlineScript: |-
              set -Eeuxo pipefail
              echo "blueGreen":$(blueGreen-acsDev)

      - ${{ if eq(parameters.blueGreen,'true') }}:
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{parameters.subscriptionName}}
            addSpnToEnvironment: true
            scriptLocation: inlineScript
            scriptType: bash
            inlineScript: |-
              set -Eeuxo pipefail
              echo "blueGreen":$(blueGreen-acsDev)
      

      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{parameters.subscriptionName}}
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |-
            set -Eeuxo pipefail
            echo "non-blueGreen":$(blueGreen-acsDev)






