parameters:
  subscriptionName:
  locationName:
  environmentName:
  subscriptionId:
  applicationCode:
  applicationShortCode: 
  environmentCategory:


jobs:
  - template: get-approval.yaml
    parameters:
      environmentName: ${{parameters.environmentName}}

  - job: printVariables
    displayName: Print variables
    dependsOn:
      - getApproval
    variables:
      - template: variables-deploy-infra.yaml
        parameters:
          subscriptionName: ${{parameters.subscriptionName}}
          locationName: ${{parameters.locationName}}
          environmentName: ${{parameters.environmentName}}
          subscriptionId: ${{parameters.subscriptionId}}
          applicationCode: ${{parameters.applicationCode}}
          applicationShortCode: ${{parameters.applicationShortCode}}
          environmentCategory: ${{parameters.environmentCategory}}
    steps:
      - checkout: none

      - template: print-pipeline-resource-variables.yaml
        parameters:
          pipelineResourceName: test

      - script: |-
          echo "parameter: subscriptionName: ${{parameters.subscriptionName}}"
          echo "parameter: locationName: ${{parameters.locationName}}"
          echo "parameter: appInsightsLocation: ${{parameters.appInsightsLocation}}"
          echo "parameter: environmentName: ${{parameters.environmentName}}"
          echo "parameter: subscriptionId: ${{parameters.subscriptionId}}"
          echo "parameter: applicationCode: ${{parameters.applicationCode}}"
          echo "parameter: applicationShortCode: ${{parameters.applicationShortCode}}"
          echo "parameter: environmentCategory: ${{parameters.environmentCategory}}"
          echo "parameter: kubernetesVersion: ${{parameters.kubernetesVersion}}"
          echo "parameter: sendgridEmail: ${{parameters.sendgridEmail}}"
          echo "variable: aksPartialName: $(aksPartialName)"
          echo "variable: appConfigurationPartialName: $(appConfigurationPartialName)"
          echo "variable: appInsightsPartialName: $(appInsightsPartialName)"
          echo "variable: armDirectory: $(armDirectory)"
          echo "variable: automationPartialName: $(automationPartialName)"
          echo "variable: blobContainerPartialName: $(blobContainerPartialName)"
          echo "variable: cosmosDbName: $(cosmosDbName)"
          echo "variable: cosmosDbAccountPartialName: $(cosmosDbAccountPartialName)"
          echo "variable: crslPlatformKeyVault: $(crslPlatformKeyVault)"
          echo "variable: defaultSasKeyName: $(defaultSasKeyName)"
          echo "variable: eventHubPartialName: $(eventHubPartialName)"
          echo "variable: functionApp1PartialName: $(functionApp1PartialName)"
          echo "variable: functionApp2PartialName: $(functionApp2PartialName)"
          echo "variable: keyVaultPartialName: $(keyVaultPartialName)"
          echo "variable: mapsPartialName: $(mapsPartialName)"
          echo "variable: omsWorkspacePartialName: $(omsWorkspacePartialName)"
          echo "variable: storageAccountPartialName: $(storageAccountPartialName)"
          echo "variable: tenantId: $(tenantId)"
          echo "variable: userObjId: $(userObjId)"
          echo "variable: aksName: $(aksName)"
          echo "variable: appConfigurationName: $(appConfigurationName)"
          echo "variable: appInsightsName: $(appInsightsName)"
          echo "variable: armParametersDirectory: $(armParametersDirectory)"
          echo "variable: armTemplatesDirectory: $(armTemplatesDirectory)"
          echo "variable: automationName: $(automationName)"
          echo "variable: blobContainerName: $(blobContainerName)"
          echo "variable: cosmosDbAccountName: $(cosmosDbAccountName)"
          echo "variable: eventHubName: $(eventHubName)"
          echo "variable: functionApp1Name: $(functionApp1Name)"
          echo "variable: functionApp2Name: $(functionApp2Name)"
          echo "variable: keyVaultName: $(keyVaultName)"
          echo "variable: mapsName: $(mapsName)"
          echo "variable: omsWorkspaceName: $(omsWorkspaceName)"
          echo "variable: resourceGroupName: $(resourceGroupName)"
          echo "variable: storageAccountName: $(storageAccountName)"
        displayName: Print variables


  - job: testCLIPowershell
    displayName: testing CLI and Powershell
    dependsOn:
      - printVariables
    variables:
      - template: variables-deploy-infra.yaml
        parameters:
          subscriptionName: ${{parameters.subscriptionName}}
          locationName: ${{parameters.locationName}}
          environmentName: ${{parameters.environmentName}}
          subscriptionId: ${{parameters.subscriptionId}}
          applicationCode: ${{parameters.applicationCode}}
          applicationShortCode: ${{parameters.applicationShortCode}}
          environmentCategory: ${{parameters.environmentCategory}}
    steps:
      - checkout: none

      - task: AzureCLI@2
        displayName: Update the service principal key for AKS
        inputs:
          azureSubscription: ${{parameters.subscriptionName}}
          scriptLocation: inlineScript
          scriptType: bash
          inlineScript: |-
            echo "im in here in bash"
            echo "##vso[task.setvariable variable=servicePrincipalId;]$env:servicePrincipalId"
            echo "##vso[task.setvariable variable=servicePrincipalKey;]$env:servicePrincipalKey"
            echo "##vso[task.setvariable variable=tenantId;]$env:tenantId"
            echo "##vso[task.setvariable variable=TestVar;]JustForTest"
          addSpnToEnvironment: true

      - task: AzurePowerShell@5
        displayName: Add System Administrators
        inputs:
          azureSubscription: ${{parameters.subscriptionName}}
          azurePowerShellVersion: latestVersion
          scriptType: inlineScript
          inline: |-
            Write-Host "hey there"
            Write-Host $env:servicePrincipalId
            Write-Host $env:servicePrincipalKey
            Write-Host $env:tenantId
            Write-Host $env:TestVar
        

      - task: AzurePowerShell@3
        displayName: Create certificate and connections on Azure Automation Account
        inputs:
          azureSubscription: ${{parameters.subscriptionName}}
          ScriptType: FilePath
          ScriptPath: pipelines/cd/ExistingTenantsADE/ExistingTenantsADEyyyyyy.ps1
          ScriptArguments: -servicePrincipalId $(automationName) -servicePrincipalKey $(resourceGroupName) -tenantId $(tenantId)
          azurePowerShellVersion: LatestVersion