trigger: none        
pool:
  vmImage: ubuntu-latest
variables:
- group: crslDev
- group: acsDev
- group: crslQa
- group: crslWkbnch
- group: chimDev
- group: chimQa
- group: chimProd
- group: psdDev
- group: psdTest
- group: psdQa
- group: psdEu
- group: psdStg
- group: psdProd
- group: emdDev
- group: emdQa
- group: emdCt
- group: kciDev
- group: kciQa 
- group: kciCt
- group: kciPr
- group: psdfireDev
- group: psdfireQa
- group: psdfireCt
- group: psdfireProd
stages:
  - stage: crslDev
    displayName: CRSL dev
    variables:
    - group: crslDev
    dependsOn:
      - checkParameters
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-crslDev)
          subscriptionName: $(subscriptionName-crslDev)
          locationName: $(locationName-crslDev)
          environmentName: $(environmentName-crslDev)
          applicationCode: $(applicationCode-crslDev)
          applicationShortCode: $(applicationShortCode-crslDev)
          environmentCategory: $(environmentCategory-crslDev)        

  - stage: acsDev
    displayName: ACS dev
    variables:
    - group: acsDev
    dependsOn:
      - checkParameters
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-acsDev)
          subscriptionName: $(subscriptionName-acsDev)
          locationName: $(locationName-acsDev)
          environmentName: $(environmentName-acsDev)
          applicationCode: $(applicationCode-acsDev)
          applicationShortCode: $(applicationShortCode-acsDev)
          environmentCategory: $(environmentCategory-acsDev)

  - stage: crslQa
    displayName: CRSL QA
    variables:
    - group: crslQa
    dependsOn:
      - crslDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-crslQa)
          subscriptionName: $(subscriptionName-crslQa)
          locationName: $(locationName-crslQa)
          environmentName: $(environmentName-crslQa)
          applicationCode: $(applicationCode-crslQa)
          applicationShortCode: $(applicationShortCode-crslQa)
          environmentCategory: $(environmentCategory-crslQa)

  - stage: crslWkbnch
    displayName: CRSL workbench
    variables:
    - group: crslWkbnch
    dependsOn:
      - crslQa
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-crslWkbnch)
          subscriptionName: $(subscriptionName-crslWkbnch)
          locationName: $(locationName-crslWkbnch)
          environmentName: $(environmentName-crslWkbnch)
          applicationCode: $(applicationCode-crslWkbnch)
          applicationShortCode: $(applicationShortCode-crslWkbnch)
          environmentCategory: $(environmentCategory-crslWkbnch)

  - stage: chimDev
    displayName: CHIM dev
    variables:
    - group: chimDev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-chimDev)
          subscriptionName: $(subscriptionName-chimDev)
          locationName: $(locationName-chimDev)
          environmentName: $(environmentName-chimDev)
          applicationCode: $(applicationCode-chimDev)
          applicationShortCode: $(applicationShortCode-chimDev)
          environmentCategory: $(environmentCategory-chimDev)

  - stage: chimQa
    displayName: CHIM QA
    variables:
    - group: chimQa
    dependsOn:
      - chimDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-chimQa)
          subscriptionName: $(subscriptionName-chimQa)
          locationName: $(locationName-chimQa)
          environmentName: $(environmentName-chimQa)
          applicationCode: $(applicationCode-chimQa)
          applicationShortCode: $(applicationShortCode-chimQa)
          environmentCategory: $(environmentCategory-chimQa)

  - stage: chimProd
    displayName: CHIM prod
    variables:
    - group: chimProd
    dependsOn:
      - chimQa
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-chimProd)
          subscriptionName: $(subscriptionName-chimProd)
          locationName: $(locationName-chimProd)
          environmentName: $(environmentName-chimProd)
          applicationCode: $(applicationCode-chimProd)
          applicationShortCode: $(applicationShortCode-chimProd)
          environmentCategory: $(environmentCategory-chimProd)

  - stage: psdDev
    displayName: PSD dev
    variables:
    - group: psdDev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdDev)
          subscriptionName: $(subscriptionName-psdDev)
          locationName: $(locationName-psdDev)
          environmentName: $(environmentName-psdDev)
          applicationCode: $(applicationCode-psdDev)
          applicationShortCode: $(applicationShortCode-psdDev)
          environmentCategory: $(environmentCategory-psdDev)
          
  - stage: psdTest
    displayName: PSD Test
    variables:
    - group: psdTest
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdTest)
          subscriptionName: $(subscriptionName-psdTest)
          locationName: $(locationName-psdTest)
          environmentName: $(environmentName-psdTest)
          applicationCode: $(applicationCode-psdTest)
          applicationShortCode: $(applicationShortCode-psdTest)
          environmentCategory: $(environmentCategory-psdTest)

  - stage: psdQa
    displayName: PSD QA
    variables:
    - group: psdQa
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdQa)
          subscriptionName: $(subscriptionName-psdQa)
          locationName: $(locationName-psdQa)
          environmentName: $(environmentName-psdQa)
          applicationCode: $(applicationCode-psdQa)
          applicationShortCode: $(applicationShortCode-psdQa)
          environmentCategory: $(environmentCategory-psdQa)

  - stage: psdEu
    displayName: PSD EU
    variables:
    - group: psdEu
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdEu)
          subscriptionName: $(subscriptionName-psdEu)
          locationName: $(locationName-psdEu)
          environmentName: $(environmentName-psdEu)
          applicationCode: $(applicationCode-psdEu)
          applicationShortCode: $(applicationShortCode-psdEu)
          environmentCategory: $(environmentCategory-psdEu)

  - stage: psdStg
    displayName: PSD staging
    variables:
    - group: psdStg
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdStg)
          subscriptionName: $(subscriptionName-psdStg)
          locationName: $(locationName-psdStg)
          environmentName: $(environmentName-psdStg)
          applicationCode: $(applicationCode-psdStg)
          applicationShortCode: $(applicationShortCode-psdStg)
          environmentCategory: $(environmentCategory-psdStg)

  - stage: psdProd
    displayName: PSD Prod
    variables:
    - group: psdProd
    dependsOn:
      - psdDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdProd)
          subscriptionName: $(subscriptionName-psdProd)
          locationName: $(locationName-psdProd)
          environmentName: $(environmentName-psdProd)
          applicationCode: $(applicationCode-psdProd)
          applicationShortCode: $(applicationShortCode-psdProd)
          environmentCategory: $(environmentCategory-psdProd)

  - stage: emdDev
    displayName: EMD dev
    variables:
    - group: emdDev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-emdDev)
          subscriptionName: $(subscriptionName-emdDev)
          locationName: $(locationName-emdDev)
          environmentName: $(environmentName-emdDev)
          applicationCode: $(applicationCode-emdDev)
          applicationShortCode: $(applicationShortCode-emdDev)
          environmentCategory: $(environmentCategory-emdDev)

  - stage: emdQa
    displayName: EMD QA
    variables:
    - group: emdQa
    dependsOn:
      - emdDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-emdQa)
          subscriptionName: $(subscriptionName-emdQa)
          locationName: $(locationName-emdQa)
          environmentName: $(environmentName-emdQa)
          applicationCode: $(applicationCode-emdQa)
          applicationShortCode: $(applicationShortCode-emdQa)
          environmentCategory: $(environmentCategory-emdQa)

  - stage: emdCt
    displayName: EMD CT
    variables:
    - group: emdCt
    dependsOn:
      - emdQa
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-emdCt)
          subscriptionName: $(subscriptionName-emdCt)
          locationName: $(locationName-emdCt)
          environmentName: $(environmentName-emdCt)
          applicationCode: $(applicationCode-emdCt)
          applicationShortCode: $(applicationShortCode-emdCt)
          environmentCategory: $(environmentCategory-emdCt)

  - stage: kciDev
    displayName: KCI dev
    variables:
    - group: kciDev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-kciDev)
          subscriptionName: $(subscriptionName-kciDev)
          locationName: $(locationName-kciDev)
          environmentName: $(environmentName-kciDev)
          applicationCode: $(applicationCode-kciDev)
          applicationShortCode: $(applicationShortCode-kciDev)
          environmentCategory: $(environmentCategory-kciDev)

  - stage: kciQa
    displayName: KCI qa
    variables:
    - group: kciQa
    dependsOn:
      - kciDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters: 
          subscriptionId: $(subscriptionId-kciQa)
          subscriptionName: $(subscriptionName-kciQa)
          locationName: $(locationName-kciQa)
          environmentName: $(environmentName-kciQa)
          applicationCode: $(applicationCode-kciQa)
          applicationShortCode: $(applicationShortCode-kciQa)
          environmentCategory: $(environmentCategory-kciQa)  

  - stage: kciCt
    displayName: KCI ct
    variables:
    - group: kciCt
    dependsOn:
      - kciQa
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-kciCt)
          subscriptionName: $(subscriptionName-kciCt)
          locationName: $(locationName-kciCt)
          environmentName: $(environmentName-kciCt)
          applicationCode: $(applicationCode-kciCt)
          applicationShortCode: $(applicationShortCode-kciCt)
          environmentCategory: $(environmentCategory-kciCt)

  - stage: kciPr
    displayName: KCI Pr
    variables:
    - group: kciPr
    dependsOn:
      - kciCt
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-kciPr)
          subscriptionName: $(subscriptionName-kciPr)
          locationName: $(locationName-kciPr)
          environmentName: $(environmentName-kciPr)
          applicationCode: $(applicationCode-kciPr)
          applicationShortCode: $(applicationShortCode-kciPr)
          environmentCategory: $(environmentCategory-kciPr)

  - stage: psdfireDev
    displayName: PSDFire Dev
    variables:
    - group: psdfireDev
    dependsOn:
      - crslWkbnch
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdfireDev)
          subscriptionName: $(subscriptionName-psdfireDev)
          locationName: $(locationName-psdfireDev)
          environmentName: $(environmentName-psdfireDev)
          applicationCode: $(applicationCode-psdfireDev)
          applicationShortCode: $(applicationShortCode-psdfireDev)
          environmentCategory: $(environmentCategory-psdfireDev)

  - stage: psdfireQa
    displayName: PSDFire QA
    variables:
    - group: psdfireQa
    dependsOn:
      - psdfireDev
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdfireQa)
          subscriptionName: $(subscriptionName-psdfireQa)
          locationName: $(locationName-psdfireQa)
          environmentName: $(environmentName-psdfireQa)
          applicationCode: $(applicationCode-psdfireQa)
          applicationShortCode: $(applicationShortCode-psdfireQa)
          environmentCategory: $(environmentCategory-psdfireQa)

  - stage: psdfireCt
    displayName: PSDFire CT
    variables:
    - group: psdfireCt
    dependsOn:
      - psdfireQa
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdfireCt)
          subscriptionName: $(subscriptionName-psdfireCt)
          locationName: $(locationName-psdfireCt)
          environmentName: $(environmentName-psdfireCt)
          applicationCode: $(applicationCode-psdfireCt)
          applicationShortCode: $(applicationShortCode-psdfireCt)
          environmentCategory: $(environmentCategory-psdfireCt)

  - stage: psdfireProd
    displayName: PSDFire Prod
    variables:
    - group: psdfireProd
    dependsOn:
      - psdfireCt
    jobs:
      - template: ../templates/steps-to-audit-helm-migration.yaml
        parameters:
          subscriptionId: $(subscriptionId-psdfireProd)
          subscriptionName: $(subscriptionName-psdfireProd)
          locationName: $(locationName-psdfireProd)
          environmentName: $(environmentName-psdfireProd)
          applicationCode: $(applicationCode-psdfireProd)
          applicationShortCode: $(applicationShortCode-psdfireProd)
          environmentCategory: $(environmentCategory-psdfireProd)