trigger: none
pr: none
resources:
  pipelines:
    - pipeline: test
      source: azure-iot-platform-dotnet.ci.test
      trigger:
        branches:
          - master
pool:
  vmImage: ubuntu-latest
variables:
- group: acsDev

stages:
  - stage: acsDev
    displayName: ACS dev
    variables:
    - group: acsDev
    
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: $(environmentName-acsDev)
          subscriptionName: $(subscriptionName-acsDev)
          applicationCode: $(applicationCode-acsDev)
          applicationShortCode: $(applicationShortCode-acsDev)
          environmentCategory: $(environmentCategory-acsDev)
          imageTag: $(_imageTag)
          blueGreen: $(blueGreen-acsDev)
          subscriptionId: $(subscriptionId-acsDev)
