trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
variables:
- group: crslDev
- group: acsDev
- group: crslQa
- group: crslWkbnch
- name: locationName
  value: centralus
stages:
  - stage: checkParameters
    displayName: Check parameters
    dependsOn: []
    jobs:
     - job: checkParameters
       displayName: Check parameters
       steps:
         - checkout: none

         - script: |-
                set -Eeuxo pipefail
                echo "testPipelineRunId : '$(testPipelineRunId)'"
                if [ -z "$(testPipelineRunId)" ]
                then
                echo "A value for the 'testPipelineRunId' variable must be provided" > /dev/stderr
                exit 1
                fi

  - stage: crslDev
    displayName: CRSL dev
    variables:
    - group: crslDev
    dependsOn: checkParameters
    condition: eq(variables['runCrslDevStage'], 'true')
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: $(subscriptionName-crslDev)
          locationName: $(locationName)
          appInsightsLocation: $(appInsightsLocation-crslDev)
          environmentName: $(environmentName-crslDev)
          subscriptionId: $(subscriptionId-crslDev)
          applicationCode: $(applicationCode-crslDev)
          applicationShortCode: $(applicationShortCode-crslDev)
          environmentCategory: $(environmentCategory-crslDev)
          kubernetesVersion: $(kubernetesVersion-crslDev)
          sendgridEmail: $(sendgridEmail-crslDev)
          aksAgentVmSize: $(aksAgentVmSize-crslDev)
          azureDevOpsProjectId: $(azureDevOpsProjectId-crslDev)
          testPipelineId: $(testPipelineId-crslDev)
          runVersion: $(runVersion-crslDev)
          testPipelineRunId: $(testPipelineRunId)
          sysAdmins: $(sysAdmins-crslDev)

  - stage: acsDev
    displayName: ACS dev
    variables:
    - group: acsDev
    dependsOn: checkParameters
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: $(subscriptionName-acsDev)
          locationName: $(locationName)
          appInsightsLocation: $(appInsightsLocation-acsDev)
          environmentName: $(environmentName-acsDev)
          subscriptionId: $(subscriptionId-acsDev)
          applicationCode: $(applicationCode-acsDev)
          applicationShortCode: $(applicationShortCode-acsDev)
          environmentCategory: $(environmentCategory-acsDev)
          kubernetesVersion: $(kubernetesVersion-acsDev)
          sendgridEmail: $(sendgridEmail-acsDev)
          aksAgentVmSize: $(aksAgentVmSize-acsDev)
          azureDevOpsProjectId: $(azureDevOpsProjectId-acsDev)
          testPipelineId: $(testPipelineId-acsDev)
          runVersion: $(runVersion-acsDev)
          testPipelineRunId: $(testPipelineRunId)
          sysAdmins: $(sysAdmins-acsDev)

  - stage: crslQa
    displayName: CRSL QA
    variables:
    - group: crslQa
    dependsOn:
      - crslDev
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: $(subscriptionName-crslQa)
          locationName: $(locationName)
          appInsightsLocation: $(appInsightsLocation-crslQa)
          environmentName: $(environmentName-crslQa)
          subscriptionId: $(subscriptionId-crslQa)
          applicationCode: $(applicationCode-crslQa)
          applicationShortCode: $(applicationShortCode-crslQa)
          environmentCategory: $(environmentCategory-crslQa)
          kubernetesVersion: $(kubernetesVersion-crslQa)
          sendgridEmail: $(sendgridEmail-crslQa)
          aksAgentVmSize: $(aksAgentVmSize-crslQa)
          azureDevOpsProjectId: $(azureDevOpsProjectId-crslQa)
          testPipelineId: $(testPipelineId-crslQa)
          runVersion: $(runVersion-crslQa)
          testPipelineRunId: $(testPipelineRunId)
          sysAdmins: $(sysAdmins-crslQa)
          
  - stage: crslWkbnch
    displayName: CRSL workbench
    variables:
    - group: crslWkbnch
    dependsOn:
      - crslQa
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: $(subscriptionName)
          locationName: $(locationName)
          appInsightsLocation: $(appInsightsLocation)
          environmentName: $(environmentName)
          subscriptionId: $(subscriptionId)
          applicationCode: $(applicationCode)
          applicationShortCode: $(applicationShortCode)
          environmentCategory: $(environmentCategory)
          kubernetesVersion: $(kubernetesVersion)
          sendgridEmail: $(sendgridEmail)
          aksAgentVmSize: $(aksAgentVmSize)
          azureDevOpsProjectId: $(azureDevOpsProjectId)
          testPipelineId: $(testPipelineId)
          runVersion: $(runVersion)
          testPipelineRunId: $(testPipelineRunId)
          sysAdmins: $(sysAdmins)